apiVersion: v1
kind: Service
metadata:
  name: reg
  namespace: campify
spec:
  type: NodePort 
  selector:
    app: campify-reg
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30502
