apiVersion: v1
kind: Service
metadata:
  name: campify-frontend-service
  namespace: campify
spec:
  type: NodePort 
  selector:
    app: campify-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
